### ISSUE TITLE
Mutlithreading under linux

### ISSUE THREAD

**Issue by prosimas** [DMST1990/ToOptiX#7]
Hi Martin, 

there seems to be an issue with the mutlithreading capability of toOptix. It seems to run in serial everytime. Can you confirm this?

Many thanks and best wishes
prosimas

**Comment by DMST1990** [comment]
Hello Prosimas,

fixed as well. Now CalculiX performs in paralell for Windows and Linux. You now you should see something like "Using up to 4 cpu(s) for spooles." in the command prompt.

(Paralellisation of ToOptix is not necessary because the 90% of the calculation time is used for solving the FEM-System with CalculiX)


Best Regards

Martin
